In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
cars=pd.read_csv("audi.csv")
cars.head()


model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [3]:
cars.shape

(10668, 9)

In [4]:
cars.dtypes

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [5]:
cars.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [24]:
X=cars.iloc[:,[0,1,3,4,5,6,7,8]]
Y= cars.iloc[:,2]
print(type(X))
print(type(Y))


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [25]:
print(X)

       model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0          0  2017             1    15735         2  150  55.4         1.4
1          5  2016             0    36203         0   20  64.2         2.0
2          0  2016             1    29946         2   30  55.4         1.4
3          3  2017             0    25952         0  145  67.3         2.0
4          2  2019             1     1998         2  145  49.6         1.0
...      ...   ...           ...      ...       ...  ...   ...         ...
10663      2  2020             1     4018         2  145  49.6         1.0
10664      2  2020             1     1978         2  150  49.6         1.0
10665      2  2020             1      609         2  150  49.6         1.0
10666      9  2017             0     8646         2  150  47.9         1.4
10667      9  2016             1    11855         2  150  47.9         1.4

[10668 rows x 8 columns]


In [26]:
print(Y)

0        12500
1        16500
2        11000
3        16800
4        17300
         ...  
10663    16999
10664    16999
10665    17199
10666    19499
10667    15999
Name: price, Length: 10668, dtype: int64


In [27]:
cars['model'].value_counts()

2     1929
9     1417
3     1381
0     1347
4      882
10     877
8      822
5      748
11     397
25     336
6      122
7      118
12      69
17      39
14      33
15      31
16      29
13      28
19      18
23      16
20      12
24       8
22       4
21       3
1        1
18       1
Name: model, dtype: int64

In [28]:
cars['transmission'].value_counts()

1    4369
2    3591
0    2708
Name: transmission, dtype: int64

In [29]:
cars['fuelType'].value_counts()

0    5577
2    5063
1      28
Name: fuelType, dtype: int64

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le=LabelEncoder()

In [32]:
cars['model']=le.fit_transform(cars['model'])
cars['transmission']=le.fit_transform(cars['transmission'])
cars['fuelType']=le.fit_transform(cars['fuelType'])

In [33]:
cars.head()

model  year  price  transmission  mileage  fuelType  tax   mpg  engineSize
0      0  2017  12500             1    15735         2  150  55.4         1.4
1      5  2016  16500             0    36203         0   20  64.2         2.0
2      0  2016  11000             1    29946         2   30  55.4         1.4
3      3  2017  16800             0    25952         0  145  67.3         2.0
4      2  2019  17300             1     1998         2  145  49.6         1.0

Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
st=StandardScaler()


In [36]:
st.fit_transform(X)

array([[-1.12354352, -0.04644979, -0.10834719, ...,  0.35714729,
         0.35755001, -0.88021837],
       [-0.16083109, -0.50783377, -1.41734817, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-1.12354352, -0.50783377, -0.10834719, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.73845855,  1.33770214, -0.10834719, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 0.60933885, -0.04644979, -1.41734817, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [ 0.60933885, -0.50783377, -0.10834719, ...,  0.35714729,
        -0.22163749, -0.88021837]])

Spliting X into training and testing data

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_tr,x_te,y_tr,y_te=train_test_split(X,Y,test_size=0.30)
print(x_tr.shape)
print(x_te.shape)
print(y_tr.shape)
print(y_te.shape)

(7467, 8)
(3201, 8)
(7467,)
(3201,)


In [39]:
from sklearn.ensemble import RandomForestRegressor

In [40]:
m1=RandomForestRegressor()

In [41]:
m1.fit(x_tr,y_tr)

RandomForestRegressor()

In [42]:
ypred_m1=m1.predict(x_te)

In [43]:
print(ypred_m1)

[13657.43 18772.45 12524.57 ... 13279.71 17042.28 70199.03]


In [44]:
print((y_te))

9287     15490
6374     19400
1730     13498
4935     53500
3784     23500
         ...  
6774     26990
7011     16490
7222     14495
3194     18000
10098    69890
Name: price, Length: 3201, dtype: int64


In [1]:
from sklearn.metrics import r2_score

In [70]:
print(r2_score(y_te,ypred_m1))

0.9587267051149809


In [47]:
ap=[['A1',2016,'Manual',33333,'Petrol',201,19,1.7]]
ap=pd.DataFrame(ap)
ap[0]=le.fit_transform(ap[0])
ap[2]=le.fit_transform(ap[2])
ap[4]=le.fit_transform(ap[4])
print(type(ap))

<class 'pandas.core.frame.DataFrame'>


In [48]:
k=m1.predict(ap)

C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [49]:
k

array([37786.87])

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
m2=LinearRegression()

In [52]:
m2.fit(x_tr,y_tr)

LinearRegression()

In [53]:
ypred_m2=m2.predict(x_te)

In [54]:
print(r2_score(y_te,ypred_m1))

0.9587267051149809


In [55]:
kk=m2.predict(ap)
kk

C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([18541.75171335])

In [56]:
from sklearn.tree import DecisionTreeRegressor

In [59]:
m3 = DecisionTreeRegressor(max_depth=5)

In [62]:
m3.fit(x_tr,y_tr)

DecisionTreeRegressor(max_depth=5)

In [63]:
ypred_m3=m3.predict(x_te)

In [67]:
print(m3.score(x_tr,y_tr))

0.864939735829603


In [68]:
print(m3.score(x_te,y_te))

0.8525068146158487


In [71]:
print(r2_score(y_te,ypred_m3))

0.8525068146158487
